package task2;

class ArchivatorException extends Exception {

    ArchivatorException(Throwable cause) {
        super(cause);
    }
}
